pipeline{
    agent any
    stages{
        stage("checkout")
        {
            steps{
                git branch:'main' , url:"https://github.com/Mayurjoshi00/test-repo-java-17-4-26.git"
            }
        }
        stage('Build')
        {
            steps
            {
                echo"Pushing the initial file to git"
                echo"trying to add"
            }
        }
        stage('test')
        {
            steps
            {
                echo"testing..."
            }
        }
    }
}